// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MonteCarlo.NET.Data;

#nullable disable

namespace MonteCarlo.NET.Migrations
{
    [DbContext(typeof(CasinoContext))]
    partial class CasinoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "e61ff799-4f47-4940-ab43-e2cfe387334f",
                            ConcurrencyStamp = "asd1",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "8ca8f07b-ab7c-488c-b3bc-1571e10100da",
                            RoleId = "e61ff799-4f47-4940-ab43-e2cfe387334f"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MonteCarlo.NET.Models.Ban", b =>
                {
                    b.Property<int>("BanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdBana");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BanId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("Data");

                    b.Property<int>("DurationDays")
                        .HasColumnType("int")
                        .HasColumnName("Dlugosc");

                    b.Property<string>("Reason")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("Przyczyna");

                    b.Property<string>("UserAccountId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("KontoUzytkownikaId");

                    b.HasKey("BanId");

                    b.HasIndex("UserAccountId");

                    b.ToTable("Ban", (string)null);
                });

            modelBuilder.Entity("MonteCarlo.NET.Models.Bet", b =>
                {
                    b.Property<int>("BetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdZakladu");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BetId"));

                    b.Property<bool>("HasWon")
                        .HasColumnType("bit")
                        .HasColumnName("czyWygral");

                    b.Property<bool>("IsRewardGranted")
                        .HasColumnType("bit")
                        .HasColumnName("czyPrzyznanoNagrode");

                    b.Property<int>("MatchId")
                        .HasColumnType("int")
                        .HasColumnName("IdMeczu");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("IdGracza");

                    b.Property<long>("StakedAmount")
                        .HasColumnType("bigint")
                        .HasColumnName("PostawionaKwota");

                    b.Property<int>("WinnerTeamId")
                        .HasColumnType("int")
                        .HasColumnName("IdZwyciezcy");

                    b.HasKey("BetId");

                    b.ToTable("Zaklady", (string)null);
                });

            modelBuilder.Entity("MonteCarlo.NET.Models.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdGry");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GameId"));

                    b.Property<double>("MinStake")
                        .HasColumnType("float")
                        .HasColumnName("MinStawka");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Nazwa");

                    b.HasKey("GameId");

                    b.ToTable("Gra", (string)null);

                    b.HasData(
                        new
                        {
                            GameId = 1,
                            MinStake = 1.0,
                            Name = "Slotsy"
                        },
                        new
                        {
                            GameId = 2,
                            MinStake = 1.0,
                            Name = "Zdrapka koniczynka"
                        },
                        new
                        {
                            GameId = 3,
                            MinStake = 1.0,
                            Name = "Zdrapka Prosta"
                        },
                        new
                        {
                            GameId = 4,
                            MinStake = 1.0,
                            Name = "Wyscigi Konne"
                        },
                        new
                        {
                            GameId = 5,
                            MinStake = 1.0,
                            Name = "Obstawianie"
                        },
                        new
                        {
                            GameId = 6,
                            MinStake = 1.0,
                            Name = "Ruletka"
                        },
                        new
                        {
                            GameId = 7,
                            MinStake = 1.0,
                            Name = "Kosci"
                        });
                });

            modelBuilder.Entity("MonteCarlo.NET.Models.GameAccount", b =>
                {
                    b.Property<int>("GameAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdGraKonto");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GameAccountId"));

                    b.Property<double>("AmountStaked")
                        .HasColumnType("float")
                        .HasColumnName("IlePostawiono");

                    b.Property<double>("AmountWon")
                        .HasColumnType("float")
                        .HasColumnName("IleWygrano");

                    b.Property<int>("GameId")
                        .HasColumnType("int")
                        .HasColumnName("IdGry");

                    b.Property<DateTime>("PlayedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("Czas");

                    b.Property<string>("UserAccountId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("KontoUzytkownikaId");

                    b.HasKey("GameAccountId");

                    b.HasIndex("GameId");

                    b.HasIndex("UserAccountId");

                    b.ToTable("GraKonto", (string)null);
                });

            modelBuilder.Entity("MonteCarlo.NET.Models.Level", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("MinimumPlayedGames")
                        .HasColumnType("bigint");

                    b.Property<int>("NumberOfLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Levele", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MinimumPlayedGames = 0L,
                            NumberOfLevel = 0
                        },
                        new
                        {
                            Id = 2,
                            MinimumPlayedGames = 5L,
                            NumberOfLevel = 1
                        },
                        new
                        {
                            Id = 3,
                            MinimumPlayedGames = 15L,
                            NumberOfLevel = 2
                        },
                        new
                        {
                            Id = 4,
                            MinimumPlayedGames = 50L,
                            NumberOfLevel = 3
                        },
                        new
                        {
                            Id = 5,
                            MinimumPlayedGames = 100L,
                            NumberOfLevel = 4
                        },
                        new
                        {
                            Id = 6,
                            MinimumPlayedGames = 500L,
                            NumberOfLevel = 5
                        },
                        new
                        {
                            Id = 7,
                            MinimumPlayedGames = 1000L,
                            NumberOfLevel = 6
                        });
                });

            modelBuilder.Entity("MonteCarlo.NET.Models.Limit", b =>
                {
                    b.Property<int>("LimitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdLimitu");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LimitId"));

                    b.Property<double>("Amount")
                        .HasColumnType("float")
                        .HasColumnName("Kwota");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("Data");

                    b.Property<string>("UserAccountId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("KontoUzytkownikaId");

                    b.HasKey("LimitId");

                    b.HasIndex("UserAccountId");

                    b.ToTable("Limit", (string)null);
                });

            modelBuilder.Entity("MonteCarlo.NET.Models.Match", b =>
                {
                    b.Property<int>("MatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MeczId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MatchId"));

                    b.Property<int>("AwayTeamGoals")
                        .HasColumnType("int");

                    b.Property<int>("AwayTeamId")
                        .HasColumnType("int");

                    b.Property<string>("AwayTeamName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("AwayTeamOdds")
                        .HasColumnType("real");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("data");

                    b.Property<int>("HomeTeamGoals")
                        .HasColumnType("int");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("int");

                    b.Property<string>("HomeTeamName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("HomeTeamOdds")
                        .HasColumnType("real");

                    b.HasKey("MatchId");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.ToTable("Mecz", (string)null);

                    b.HasData(
                        new
                        {
                            MatchId = 1,
                            AwayTeamGoals = 2,
                            AwayTeamId = 1,
                            AwayTeamName = "Java FC",
                            AwayTeamOdds = 2f,
                            Date = new DateOnly(2025, 2, 2),
                            HomeTeamGoals = 2,
                            HomeTeamId = 2,
                            HomeTeamName = "Olimpia .NeT",
                            HomeTeamOdds = 3f
                        },
                        new
                        {
                            MatchId = 2,
                            AwayTeamGoals = 2,
                            AwayTeamId = 1,
                            AwayTeamName = "Java FC",
                            AwayTeamOdds = 2f,
                            Date = new DateOnly(2025, 2, 3),
                            HomeTeamGoals = 2,
                            HomeTeamId = 2,
                            HomeTeamName = "Olimpia .NeT",
                            HomeTeamOdds = 3f
                        });
                });

            modelBuilder.Entity("MonteCarlo.NET.Models.Report", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdZgloszenia");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("Tresc");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("Data");

                    b.Property<string>("Notes")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("Notatki");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Tytul");

                    b.Property<string>("UserAccountId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("KontoUzytkownikaId");

                    b.HasKey("ReportId");

                    b.HasIndex("UserAccountId");

                    b.ToTable("Zgloszenie", (string)null);
                });

            modelBuilder.Entity("MonteCarlo.NET.Models.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DruzynaId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeamId"));

                    b.Property<string>("League")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeamId");

                    b.ToTable("Druzyna", (string)null);

                    b.HasData(
                        new
                        {
                            TeamId = 1,
                            League = "Premier League",
                            Name = "Olimpia .NeT"
                        },
                        new
                        {
                            TeamId = 2,
                            League = "Premier League",
                            Name = "Java FC"
                        });
                });

            modelBuilder.Entity("MonteCarlo.NET.Models.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdTransakcji");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<double>("Amount")
                        .HasColumnType("float")
                        .HasColumnName("Kwota");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("Data");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Typ");

                    b.Property<string>("UserAccountId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("KontoUzytkownikaId");

                    b.HasKey("TransactionId");

                    b.HasIndex("UserAccountId");

                    b.ToTable("Transakcja", (string)null);
                });

            modelBuilder.Entity("MonteCarlo.NET.Models.UserAccount", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<double?>("Balance")
                        .HasColumnType("float")
                        .HasColumnName("Saldo");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Imie");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Nazwisko");

                    b.Property<int?>("Level")
                        .HasColumnType("int");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "8ca8f07b-ab7c-488c-b3bc-1571e10100da",
                            AccessFailedCount = 0,
                            Balance = 0.0,
                            ConcurrencyStamp = "6b84402b-98b1-49d9-a10a-7a407cb1aa31",
                            Email = "admin@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Admin",
                            LastName = "Admin",
                            Level = 0,
                            LockoutEnabled = true,
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "ADMIN@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEFxm56pT3lkZSkHT1RKVEG2AWclz4TGAj89Tc4CAkgZrXfRtxC/6zj0+0T6F1UdPvA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "115778a3-6593-4ad3-a680-8c83d11a9f80",
                            TwoFactorEnabled = false,
                            UserName = "admin@gmail.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MonteCarlo.NET.Models.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MonteCarlo.NET.Models.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MonteCarlo.NET.Models.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MonteCarlo.NET.Models.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MonteCarlo.NET.Models.Ban", b =>
                {
                    b.HasOne("MonteCarlo.NET.Models.UserAccount", "UserAccount")
                        .WithMany("Bans")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("MonteCarlo.NET.Models.GameAccount", b =>
                {
                    b.HasOne("MonteCarlo.NET.Models.Game", "Game")
                        .WithMany("GameAccounts")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MonteCarlo.NET.Models.UserAccount", "UserAccount")
                        .WithMany("GameAccounts")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("MonteCarlo.NET.Models.Limit", b =>
                {
                    b.HasOne("MonteCarlo.NET.Models.UserAccount", "UserAccount")
                        .WithMany("Limits")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("MonteCarlo.NET.Models.Match", b =>
                {
                    b.HasOne("MonteCarlo.NET.Models.Team", "AwayTeam")
                        .WithMany()
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MonteCarlo.NET.Models.Team", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");
                });

            modelBuilder.Entity("MonteCarlo.NET.Models.Report", b =>
                {
                    b.HasOne("MonteCarlo.NET.Models.UserAccount", "UserAccount")
                        .WithMany("Reports")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("MonteCarlo.NET.Models.Transaction", b =>
                {
                    b.HasOne("MonteCarlo.NET.Models.UserAccount", "UserAccount")
                        .WithMany("Transactions")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("MonteCarlo.NET.Models.Game", b =>
                {
                    b.Navigation("GameAccounts");
                });

            modelBuilder.Entity("MonteCarlo.NET.Models.UserAccount", b =>
                {
                    b.Navigation("Bans");

                    b.Navigation("GameAccounts");

                    b.Navigation("Limits");

                    b.Navigation("Reports");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
